services:
  db:
    image: mysql:8.4
    container_name: app_backend_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: app_db
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: